name: Auto-approve Dependabot
on: pull_request_target

permissions:
    contents: write
    pull-requests: write

jobs:
    auto-merge:
        name: Approve and merge PR
        runs-on: ubuntu-latest
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        steps:
            - name: Mint a GitHub App installation token
              uses: actions/create-github-app-token@v3
              id: app-token
              with:
                  client-id: ${{ secrets.CLIENT_ID }}
                  private-key: ${{ secrets.APP_PRIVATE_KEY }}
            - name: Approve and enable auto-merge
              uses: fastify/github-action-merge-dependabot@v3
              with:
                  github-token: ${{ steps.app-token.outputs.token }}
                  merge-method: merge
                  use-github-auto-merge: true
